# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .app import *
from .framework import *
from .job import *
from .provider import *
from ._inputs import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "ketch",
  "mod": "index/app",
  "fqn": "pulumi_ketch",
  "classes": {
   "ketch:index/app:App": "App"
  }
 },
 {
  "pkg": "ketch",
  "mod": "index/framework",
  "fqn": "pulumi_ketch",
  "classes": {
   "ketch:index/framework:Framework": "Framework"
  }
 },
 {
  "pkg": "ketch",
  "mod": "index/job",
  "fqn": "pulumi_ketch",
  "classes": {
   "ketch:index/job:Job": "Job"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "ketch",
  "token": "pulumi:providers:ketch",
  "fqn": "pulumi_ketch",
  "class": "Provider"
 }
]
"""
)
