# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['FrameworkArgs', 'Framework']

@pulumi.input_type
class FrameworkArgs:
    def __init__(__self__, *,
                 framework: pulumi.Input['FrameworkFrameworkArgs']):
        """
        The set of arguments for constructing a Framework resource.
        """
        pulumi.set(__self__, "framework", framework)

    @property
    @pulumi.getter
    def framework(self) -> pulumi.Input['FrameworkFrameworkArgs']:
        return pulumi.get(self, "framework")

    @framework.setter
    def framework(self, value: pulumi.Input['FrameworkFrameworkArgs']):
        pulumi.set(self, "framework", value)


@pulumi.input_type
class _FrameworkState:
    def __init__(__self__, *,
                 framework: Optional[pulumi.Input['FrameworkFrameworkArgs']] = None):
        """
        Input properties used for looking up and filtering Framework resources.
        """
        if framework is not None:
            pulumi.set(__self__, "framework", framework)

    @property
    @pulumi.getter
    def framework(self) -> Optional[pulumi.Input['FrameworkFrameworkArgs']]:
        return pulumi.get(self, "framework")

    @framework.setter
    def framework(self, value: Optional[pulumi.Input['FrameworkFrameworkArgs']]):
        pulumi.set(self, "framework", value)


class Framework(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 framework: Optional[pulumi.Input[pulumi.InputType['FrameworkFrameworkArgs']]] = None,
                 __props__=None):
        """
        Create a Framework resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: FrameworkArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Framework resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param FrameworkArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FrameworkArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 framework: Optional[pulumi.Input[pulumi.InputType['FrameworkFrameworkArgs']]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FrameworkArgs.__new__(FrameworkArgs)

            if framework is None and not opts.urn:
                raise TypeError("Missing required property 'framework'")
            __props__.__dict__["framework"] = framework
        super(Framework, __self__).__init__(
            'ketch:index/framework:Framework',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            framework: Optional[pulumi.Input[pulumi.InputType['FrameworkFrameworkArgs']]] = None) -> 'Framework':
        """
        Get an existing Framework resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _FrameworkState.__new__(_FrameworkState)

        __props__.__dict__["framework"] = framework
        return Framework(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def framework(self) -> pulumi.Output['outputs.FrameworkFramework']:
        return pulumi.get(self, "framework")

