// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface AppApp {
    cnames?: pulumi.Input<pulumi.Input<string>[]>;
    framework: pulumi.Input<string>;
    image: pulumi.Input<string>;
    name: pulumi.Input<string>;
    ports?: pulumi.Input<pulumi.Input<number>[]>;
    processes?: pulumi.Input<pulumi.Input<inputs.AppAppProcess>[]>;
    routingSettings?: pulumi.Input<inputs.AppAppRoutingSettings>;
    units?: pulumi.Input<number>;
    version?: pulumi.Input<number>;
}

export interface AppAppProcess {
    cmds?: pulumi.Input<pulumi.Input<string>[]>;
    name?: pulumi.Input<string>;
}

export interface AppAppRoutingSettings {
    weight?: pulumi.Input<number>;
}

export interface FrameworkFramework {
    appQuotaLimit?: pulumi.Input<number>;
    ingressController: pulumi.Input<inputs.FrameworkFrameworkIngressController>;
    name: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
}

export interface FrameworkFrameworkIngressController {
    className: pulumi.Input<string>;
    clusterIssuer?: pulumi.Input<string>;
    serviceEndpoint: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface JobJob {
    backoffLimit?: pulumi.Input<number>;
    completions?: pulumi.Input<number>;
    containers?: pulumi.Input<pulumi.Input<inputs.JobJobContainer>[]>;
    description?: pulumi.Input<string>;
    framework: pulumi.Input<string>;
    name: pulumi.Input<string>;
    parallelism?: pulumi.Input<number>;
    policy?: pulumi.Input<inputs.JobJobPolicy>;
    suspend?: pulumi.Input<boolean>;
    type?: pulumi.Input<string>;
    version?: pulumi.Input<string>;
}

export interface JobJobContainer {
    commands: pulumi.Input<pulumi.Input<string>[]>;
    image: pulumi.Input<string>;
    name: pulumi.Input<string>;
}

export interface JobJobPolicy {
    restartPolicy: pulumi.Input<string>;
}
