// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface AppApp {
    cnames?: string[];
    framework: string;
    image: string;
    name: string;
    ports?: number[];
    processes?: outputs.AppAppProcess[];
    routingSettings?: outputs.AppAppRoutingSettings;
    units?: number;
    version?: number;
}

export interface AppAppProcess {
    cmds?: string[];
    name?: string;
}

export interface AppAppRoutingSettings {
    weight?: number;
}

export interface FrameworkFramework {
    appQuotaLimit?: number;
    ingressController: outputs.FrameworkFrameworkIngressController;
    name: string;
    namespace?: string;
}

export interface FrameworkFrameworkIngressController {
    className: string;
    clusterIssuer?: string;
    serviceEndpoint: string;
    type: string;
}

export interface JobJob {
    backoffLimit?: number;
    completions?: number;
    containers?: outputs.JobJobContainer[];
    description?: string;
    framework: string;
    name: string;
    parallelism?: number;
    policy?: outputs.JobJobPolicy;
    suspend?: boolean;
    type?: string;
    version?: string;
}

export interface JobJobContainer {
    commands: string[];
    image: string;
    name: string;
}

export interface JobJobPolicy {
    restartPolicy: string;
}
