// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./app";
export * from "./framework";
export * from "./job";
export * from "./provider";

// Export sub-modules:
import * as types from "./types";

export {
    types,
};

// Import resources to register:
import { App } from "./app";
import { Framework } from "./framework";
import { Job } from "./job";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "ketch:index/app:App":
                return new App(name, <any>undefined, { urn })
            case "ketch:index/framework:Framework":
                return new Framework(name, <any>undefined, { urn })
            case "ketch:index/job:Job":
                return new Job(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("ketch", "index/app", _module)
pulumi.runtime.registerResourceModule("ketch", "index/framework", _module)
pulumi.runtime.registerResourceModule("ketch", "index/job", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("ketch", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:ketch") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
